- .gitignore
- .npmignore
- package.json
- src/bookmarklet.js
This PR adds a bookmarklet as suggested in #1 
You can try it out by right clicking in your browser's bookmarks bar, then click "add page" and paste the code below in the url field:
```javascript
javascript:(function()%7B(function()%7B%22use%20strict%22%3Bfunction%20e(e)%7Breturn%20Array.prototype.slice.call(window.document.querySelectorAll(e))%7Dfunction%20t()%7Balert(%22Sorry%2C%20sakura%20styles%20could%20not%20be%20applied%20to%20this%20page.%22)%7Dfunction%20r()%7Bvar%20t%3De(%22link%22).filter(function(e)%7Breturn%22stylesheet%22%3D%3D%3De.getAttribute(%22rel%22)%26%26e!%3D%3Dn%7D)%2Cr%3De(%22style%22)%2Co%3Dt.concat(r)%3Bo.forEach(function(e)%7Be.parentElement.removeChild(e)%7D)%7Dvar%20n%3Dwindow.document.createElement(%22link%22)%3Bn.addEventListener(%22error%22%2Ct)%2Cn.addEventL …
```
> add bookmarklet

- css/sakura-dark-solarized.css
- css/sakura-dark.css
- css/sakura-earthly.css
- css/sakura-vader.css
- css/sakura.css
- scss/_main.scss
> checkboxes have a dotted outline for easier keyboard navigation

- README.md
> Add package manager install instructions

- README.md
Sakura was just what I needed to get this website up and running! Thank you for creating the classless CSS.
> README: Add ChocoPy as user of Sakura

- README.md
> added ninjas.cl :)

- README.md
I have created an R package which generates HTML documents with your CSS frameworks.
It seems working perfectly!!
Thank you for your great work!!!
> Add a site which uses sakura

- css/sakura-dark-solarized.css
- css/sakura-dark.css
- css/sakura-earthly.css
- css/sakura-vader.css
- css/sakura.css
- scss/_main.scss
This PR improves the overall spacing. Adds a lot more room to breathe.
> feature: improve spacing using margins

- css/sakura-dark-solarized.css
- css/sakura-dark.css
- css/sakura-earthly.css
- css/sakura-ink.css
- css/sakura-vader.css
- css/sakura.css
- package-lock.json
- scss/_main.scss
#42 Fix for button disabled pointer events. Has been tested on both Firefox and Chrome
> #42 Fix for button disabled pointer events

- css/sakura-dark-solarized.css
- css/sakura-dark.css
- css/sakura-earthly.css
- css/sakura-ink.css
- css/sakura-vader.css
- css/sakura.css
- scss/_main.scss
- test.html
#53 Updating `video` with a large video in test.html and to use the same styles as img.
> Updating video to display as per img

- README.md
I'm also planning to add a selection of sakura themes for MousikóFídi
itself, but for now the main website happily uses it.
> Add mousikofidi.info to the list of sites using Sakura

- README.md
Sakura definitely helped me make it look much better without any effort. Thanks for maintaining it!
> Add ocamlbook.org to the list of Sakura users

- README.md
Thank you for the great work! It seems to be the best classsless css framework around :100:
> Add MonkeyJungleJuice to the list of Sakura users

- README.md
- css/sakura-pink.css
- scss/sakura-pink.scss
_I was wondering why a css framework named sakura but no pink color theme :D_
I also added my site `reinforce.moe/about-en.md` to the sites list in this PR. Your framework saved my day to write a css from zero. Appreciated!
Screenshots Demo
> Create new theme in pink color

- README.md
Well, with some tweaks, of course, to fit bearblog.dev :)
> Another happy user! :)

- README.md
I've started that project yesterday BTW
I discovered the lib from other activities (probably stars) then did a PoC using a Golang cloud function with an article parser library I already used and I think the result is as good as the alternatives provide.
I am the backend-like of guy and for the frontend, I often use things like Chakra UI but sometimes React is pretty overkill.
That site neither uses flexbox nor javascript and does all the page crunching on the cloud function.
Awesome work, guys. The styling was really the easiest part of this project xD
The repo: https://github.com/lucasew/readability-web
> add https://articleparser.vercel.app/ as sakura user

- README.md
Switched to custom `CSS`, thanks for Sakura again!
> Remove mkws.sh from "Sites using Sakura"

- .github/workflows/ci.yml
- CONTRIBUTING.md
This uses a GitHub action to build the CSS files. If possible, it will attempt to commit the built
CSS.
https://github.com/spenserblack/sakura.css/commit/474d836a7bf1c7e4e9558ce3ccf8f09b11476e1c
https://github.com/spenserblack/sakura.css/actions/runs/2699137732
https://github.com/spenserblack/sakura.css/pull/2
For #77 (first list item)
> Build CSS with GitHub action

- index.html
- package-lock.json
- package.json
- preview.mjs
I want to migrate to vite for both 
- local dev preview
- deployment previews (per branch, and later the demo website as well)
I also want to migrate to postcss instead of node-sass in the future.
This PR is a starting step in that direction, I have based this code on TOP OF the code created by @spenserblack in #96. I have ended up missing some of the commits, still figuring this out 🙈
> ⚡️ Vite preview and vercel deployments

- README.md
Dear maintainer,
I added my Tech Blog to the "Sites using sakura" section.
I'm a really happy user of Sakura.css and find its color pallet well tuned, with different flavors for choice. That is something, that's not a given with many other minimal classless CSS frameworks.
I built my Tech Blog around Sakura.css: "Frost Kiwi's Secrets", https://blog.frost.kiwi/ .
The 11ty source code is public: https://github.com/FrostKiwi/treasurechest
> New "Sites using sakura" addition

- README.md
> Update README.MD - adding my site

- README.md
Hello,
I wanted to add my personal blog to the Readme as a site using Sakura. As a design-challenged software engineer, I appreciated how one CSS file made the blog look so much better. Thank you for your work!
> Adds kylenazario.com to readme
